[package]
name = "factory-legacy-meta"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.factory-legacy]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.5"
default-features = false