[package]
name = "timestamp-oracle-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.timestamp-oracle]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "=0.53.2"
default-features = false
