[package]
name = "farm-concentrated-liq-abi"
version = "0.0.0"
authors = ["MultiversX <contact@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.farm-concentrated-liq]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.46.1"
default-features = false
