[package]
name = "farm-v12-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.farm-v12]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.52.3"
default-features = false
