[package]
name = "contexts"
version = "0.0.0"
authors = [ "catalin-neagu <catalin.neagu@elrond.com>",]
edition = "2018"

[lib]
path = "src/mod.rs"

[dependencies.common_structs_old]
path = "../../../common_structs_old"

[dependencies.common_errors_old]
path = "../../../common_errors_old"

[dependencies.farm_token]
path = "../farm_token"

[dependencies.rewards]
path = "../rewards"

[dependencies.token_send]
path = "../../token_send"

[dependencies.token_merge_old]
path = "../../token_merge_old"

[dependencies.config]
path = "../config"

[dependencies.elrond-wasm]
version = "=0.28.0"
