[[bin]]
name = "interactor"
path = "src/dex_interact.rs"

[package]
name = "interactor"
version = "0.0.0"
authors = [""]
edition = "2021"
publish = false

[dependencies]
toml = "0.8.6"

[dependencies.clap]
version = "4.4.7"
features = ["derive"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.multiversx-sc]
version = "=0.50.3"

[dependencies.multiversx-sc-modules]
version = "=0.50.3"

[dependencies.multiversx-sc-snippets]
version = "=0.50.3"

[dependencies.multiversx-sc-scenario]
version = "=0.50.3"

[dependencies.proxies]
path = "proxies"

[dependencies.common_structs]
path = "../../common/common_structs"
