[package]
name = "events"
version = "0.0.0"
authors = [ "catalin-neagu <catalin.neagu@elrond.com>",]
edition = "2018"

[lib]
path = "src/events.rs"

[dependencies.common_structs_old]
path = "../../../common_structs_old"

[dependencies.common_errors_old]
path = "../../../common_errors_old"

[dependencies.contexts]
path = "../contexts"

[dependencies.elrond-wasm]
version = "=0.28.0"
