[package]
name = "proxy-dex-legacy-meta"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.proxy-dex-legacy]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.52.3"
default-features = false
