[package]
name = "router"
version = "0.0.0"
authors = ["MultiversX <contact@multiversx.com>"]
edition = "2021"
publish = false

[lib]
path = "src/contract.rs"

[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.permissions_module]
path = "../../common/modules/permissions_module"

[dependencies.token_send]
path = "../../common/modules/token_send"

[dependencies.pausable]
path = "../../common/modules/pausable"

[dependencies.multiversx-sc]
version = "=0.50.3"
features = ["esdt-token-payment-legacy-decode"]

[dependencies.pair]
path = "../pair"

[dependencies.locking_module]
path = "../../common/modules/locking_module"

[dependencies.simple-lock]
path = "../../locked-asset/simple-lock"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.50.3"
