[package]
name = "proxy-deployer"
version = "0.0.0"
authors = ["MultiversX <contact@multiversx.com>"]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "=0.53.2"
features = ["esdt-token-payment-legacy-decode"]

[dependencies.farm-staking]
path = "../../farm-staking/farm-staking"

[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.permissions_module]
path = "../../common/modules/permissions_module"

[dependencies.pausable]
path = "../../common/modules/pausable"

[dependencies.utils]
path = "../../common/modules/utils"

[dependencies.farm-boosted-yields]
path = "../../energy-integration/farm-boosted-yields"

[dev-dependencies]
num-bigint = "0.4.2"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.53.2"

[dev-dependencies.farm_token]
path = "../../common/modules/farm/farm_token"

[dev-dependencies.timestamp-oracle]
path = "../../energy-integration/timestamp-oracle"
