name: CI

on:
  push:
    branches: [ main, feat/*, actually-implementing-buckets ]
  pull_request:
    branches: [ main, feat/*, actually-implementing-buckets ]

permissions:
  actions: write
  checks: write
  contents: write
  id-token: write
  issues: write
  discussions: write
  pull-requests: write
  statuses: write

jobs:
  contracts:
    name: Contracts
    uses: ElrondNetwork/elrond-actions/.github/workflows/contracts.yml@634134e3b708be36049d6cc8b3151069a496863d
    with:
      rust-toolchain: nightly-2022-10-16
      vmtools-version: v1.4.60
      extra-build-args: --ignore-eei-checks
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
